<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HappyGopher.Extensibility\HappyGopher.Extensibility.csproj" />
    <ProjectReference Include="..\HappyGopher.TestPlugin\HappyGopher.TestPlugin.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\HappyGopher\HappyGopher.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

<Target Name="CopyTestPlugin" AfterTargets="Build">
	<ItemGroup>
		<TestPluginFiles Include="..\HappyGopher.TestPlugin\bin\$(Configuration)\net10.0\**\*" />
	</ItemGroup>

	<Copy
		SourceFiles="@(TestPluginFiles)"
		DestinationFiles="@(TestPluginFiles->'$(OutDir)TestPlugin\%(RecursiveDir)%(Filename)%(Extension)')"
		SkipUnchangedFiles="true" />
</Target>

</Project>
